spring.application.name=Evaluation-and-Decision-Service
server.port=8084

# Database
spring.datasource.url=jdbc:postgresql://ep-mute-pine-al4dfni6-pooler.c-3.eu-central-1.aws.neon.tech/evaluation_decision_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.query.plan_cache_max_size=2048
spring.jpa.properties.hibernate.query.plan_parameter_metadata_max_size=128

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Kafka
spring.kafka.bootstrap-servers=d7t38qae1n5c11g1j9i0.any.eu-central-1.mpx.prd.cloud.redpanda.com:9092
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="slasher" password="${KAFKA_PASSWORD}";
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=evaluation-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Service URLs
services.user-management.url=https://user-management-service-2zr5.onrender.com
services.startup-application.url=https://startup-application-service.onrender.com
services.ai-assessment.url=https://ai-assessment-service.onrender.com